### PR TITLE
Define all the endpoints with dummy implementations for the supported methods

### PR DESCRIPTION
**Pull request by felipet**
All the endpoints listed in [GH-12] have been defined in the OpenAPI doc (but those mentioned to be postponed in the same issue).
Some data objects have been added too. Though it was not in the scope of the initial task, during the definition of the endpoints in the API docs, it made sense to define first data objects. Otherwise, the endpoints would have been too empty.

### CODE REVIEW

**Comment by vera-zhurba** [comment]
I suggest adding a field for an ingredient's amount in the Recipe endpoint.

**Comment by vera-zhurba** [comment]
And fixing the following error: 

Resolver error at paths./author/{AuthorId}.delete.requestBody.content.application/json.schema.$ref
Could not resolve reference: Could not resolve pointer: /components/schemas/AuthorId does not exist in document

**Comment by felipet** [comment]
> Rating in Recipe should not be obligatory.

Fixed in #2d38fb8.

**Comment by felipet** [comment]
> I suggest adding a field for an ingredient's amount in the Recipe endpoint.

I implemented the relation between recipes and ingredients, now, you can see how it would end in a JSON in the example contained in the API docs. Fixed in #2d38fb8.

**Comment by felipet** [comment]
> And fixing the following error:
> 
> Resolver error at `paths./author/{AuthorId}.delete.requestBody.content.application/json.schema.$ref` Could not resolve reference: Could not resolve pointer: /components/schemas/AuthorId does not exist in document

Fixed in #737922c

**Comment by vera-zhurba** [comment]
I guess there should be a POST method in the /author/{id} endpoint so we can create new users. Or any other valid way to register new users.

**Comment by felipet** [comment]
> I guess there should be a POST method in the /author/{id} endpoint so we can create new users. Or any other valid way to register new users.

Fixed in #5c65c18

**Review by vera-zhurba — APPROVED** [review]

**Pull request merged**
